# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "facebook"
name = "Facebook"
url = "https://www.facebook.com/profile.php?id=100087432529233"

[social.params]
icon = "brand-facebook"

[[social]]
identifier = "instagram"
name = "Instagram"
url = "https://www.instagram.com/plataformaalbassal/"

[social.params]
icon = "brand-instagram"


[[social]]
identifier = "ivoox"
name = "Ivoox"
url = "https://www.ivoox.com/en/podcast-mi-reino-si-es-este-mundo_sq_f11864620_1.html"

[social.params]
icon = "brand-ivoox"

[[social]]
identifier = "spotify"
name = "Spotify"
url = "https://open.spotify.com/show/1AXKe3QfQaJ4tvtEYbZcyg"

[social.params]
icon = "brand-spotify"

[[social]]
identifier = "z-amazon-music"
name = "zAmazon Music"
url = "https://music.amazon.es/podcasts/09220d38-8264-48c6-94d5-1ca311b4d04c/mi-reino-s%C3%AD-es-de-este-mundo"

[social.params]
icon = "brand-amazon-music"